=== TINF23B6/Vereinskalender/xml/calendar_month.dtd
<!ELEMENT calendar (failedLogin, userLoggedIn, username, isAdmin, dateWrong, timeWrong, newEventType, editEvent, id, name, date_day, date_month, date_year, time_period_beginn, time_period_ende, place, type, clubs0, clubs1, points0, points1, info_text, notice, pointsTableActive, month, year, month_btn*, home_path, path_month_btn, current_path, new_path_points_table_btn, path_week, path_year, path_month, new_path_left, new_path_today, new_path_right, date_today, calendar_size, day_month*)>

<!ELEMENT failedLogin (#PCDATA)>
<!ELEMENT userLoggedIn (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT isAdmin (#PCDATA)>
<!ELEMENT dateWrong (#PCDATA)>
<!ELEMENT timeWrong (#PCDATA)>
<!ELEMENT newEventType (#PCDATA)>
<!ELEMENT editEvent (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT date_day (#PCDATA)>
<!ELEMENT date_month (#PCDATA)>
<!ELEMENT date_year (#PCDATA)>
<!ELEMENT time_period_beginn (#PCDATA)>
<!ELEMENT time_period_ende (#PCDATA)>
<!ELEMENT place (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT clubs0 (#PCDATA)>
<!ELEMENT clubs1 (#PCDATA)>
<!ELEMENT points0 (#PCDATA)>
<!ELEMENT points1 (#PCDATA)>
<!ELEMENT info_text (#PCDATA)>
<!ELEMENT notice (#PCDATA)>
<!ELEMENT pointsTableActive (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month_btn (index, name_month)+>
<!ELEMENT home_path (#PCDATA)>
<!ELEMENT path_month_btn (#PCDATA)>
<!ELEMENT current_path (#PCDATA)>
<!ELEMENT new_path_points_table_btn (#PCDATA)>
<!ELEMENT path_week (#PCDATA)>
<!ELEMENT path_year (#PCDATA)>
<!ELEMENT path_month (#PCDATA)>
<!ELEMENT new_path_left (#PCDATA)>
<!ELEMENT new_path_today (#PCDATA)>
<!ELEMENT new_path_right (#PCDATA)>
<!ELEMENT date_today (#PCDATA)>
<!ELEMENT calendar_size (#PCDATA)>
<!ELEMENT day_month (number, date, day_number, in_shown_month)+>

<!ELEMENT index (#PCDATA)>
<!ELEMENT name_month (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT day_number (#PCDATA)>
<!ELEMENT in_shown_month (#PCDATA)>

=== TINF23B6/Vereinskalender/xml/calendar.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE calendar SYSTEM 'calendar_month.dtd'> 
<calendar> 
	<failedLogin>false</failedLogin>
	<userLoggedIn>false</userLoggedIn>
	<username><![CDATA[]]></username>
	<isAdmin></isAdmin>
	<dateWrong></dateWrong>
	<timeWrong></timeWrong>
	<newEventType></newEventType>
	<editEvent></editEvent>
	<id><![CDATA[]]></id>
	<name><![CDATA[]]></name>
	<date_day><![CDATA[]]></date_day>
	<date_month><![CDATA[]]></date_month>
	<date_year><![CDATA[]]></date_year>
	<time_period_beginn><![CDATA[]]></time_period_beginn>
	<time_period_ende><![CDATA[]]></time_period_ende>
	<place><![CDATA[]]></place>
	<type><![CDATA[]]></type>
	<clubs0><![CDATA[]]></clubs0>
	<clubs1><![CDATA[]]></clubs1>
	<points0><![CDATA[]]></points0>
	<points1><![CDATA[]]></points1>
	<info_text><![CDATA[]]></info_text>
	<notice><![CDATA[]]></notice>
	<pointsTableActive>false</pointsTableActive>
	<month>Februar</month>
	<year>2024</year>
	<month_btn>
		<index>01</index>
		<name_month>Januar</name_month>
	</month_btn>
	<month_btn>
		<index>02</index>
		<name_month>Februar</name_month>
	</month_btn>
	<month_btn>
		<index>03</index>
		<name_month>MÃ¤rz</name_month>
	</month_btn>
	<month_btn>
		<index>04</index>
		<name_month>April</name_month>
	</month_btn>
	<month_btn>
		<index>05</index>
		<name_month>Mai</name_month>
	</month_btn>
	<month_btn>
		<index>06</index>
		<name_month>Juni</name_month>
	</month_btn>
	<month_btn>
		<index>07</index>
		<name_month>Juli</name_month>
	</month_btn>
	<month_btn>
		<index>08</index>
		<name_month>August</name_month>
	</month_btn>
	<month_btn>
		<index>09</index>
		<name_month>September</name_month>
	</month_btn>
	<month_btn>
		<index>10</index>
		<name_month>Oktober</name_month>
	</month_btn>
	<month_btn>
		<index>11</index>
		<name_month>November</name_month>
	</month_btn>
	<month_btn>
		<index>12</index>
		<name_month>Dezember</name_month>
	</month_btn>
	<home_path><![CDATA[http://localhost/Vereinskalender/home.php]]></home_path>
	<path_month_btn><![CDATA[http://localhost/Vereinskalender/calendar.php?view=month&pointsTableActive=false]]></path_month_btn>
	<current_path><![CDATA[http://localhost/Vereinskalender/calendar.php?view=month&pointsTableActive=false&day=01&month=02&year=2024]]></current_path>
	<new_path_points_table_btn><![CDATA[http://localhost/Vereinskalender/calendar.php?view=month&pointsTableActive=true&day=01&month=02&year=2024]]></new_path_points_table_btn>
	<path_week><![CDATA[http://localhost/Vereinskalender/calendar.php?view=week&pointsTableActive=false&day=01&month=02&year=2024]]></path_week>
	<path_year><![CDATA[http://localhost/Vereinskalender/calendar.php?view=year&pointsTableActive=false&day=01&month=02&year=2024]]></path_year>
	<path_month><![CDATA[http://localhost/Vereinskalender/calendar.php?view=month&pointsTableActive=false&day=01&month=02&year=2024]]></path_month>
	<new_path_left><![CDATA[http://localhost/Vereinskalender/calendar.php?view=month&pointsTableActive=false&day=01&month=01&year=2024]]></new_path_left>
	<new_path_today><![CDATA[http://localhost/Vereinskalender/calendar.php?view=month&pointsTableActive=false&day=04&month=08&year=2024]]></new_path_today>
	<new_path_right><![CDATA[http://localhost/Vereinskalender/calendar.php?view=month&pointsTableActive=false&day=01&month=03&year=2024]]></new_path_right>
	<date_today>2024-08-04</date_today>
	<calendar_size>small</calendar_size> 
	<day_month> 
		<number>0</number> 
		<date>2024-01-29</date> 
		<day_number>29</day_number> 
		<in_shown_month> outside-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>1</number> 
		<date>2024-01-30</date> 
		<day_number>30</day_number> 
		<in_shown_month> outside-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>2</number> 
		<date>2024-01-31</date> 
		<day_number>31</day_number> 
		<in_shown_month> outside-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>3</number> 
		<date>2024-02-01</date> 
		<day_number>01</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>4</number> 
		<date>2024-02-02</date> 
		<day_number>02</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>5</number> 
		<date>2024-02-03</date> 
		<day_number>03</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>6</number> 
		<date>2024-02-04</date> 
		<day_number>04</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>7</number> 
		<date>2024-02-05</date> 
		<day_number>05</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>8</number> 
		<date>2024-02-06</date> 
		<day_number>06</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>9</number> 
		<date>2024-02-07</date> 
		<day_number>07</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>10</number> 
		<date>2024-02-08</date> 
		<day_number>08</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>11</number> 
		<date>2024-02-09</date> 
		<day_number>09</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>12</number> 
		<date>2024-02-10</date> 
		<day_number>10</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>13</number> 
		<date>2024-02-11</date> 
		<day_number>11</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>14</number> 
		<date>2024-02-12</date> 
		<day_number>12</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>15</number> 
		<date>2024-02-13</date> 
		<day_number>13</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>16</number> 
		<date>2024-02-14</date> 
		<day_number>14</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>17</number> 
		<date>2024-02-15</date> 
		<day_number>15</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>18</number> 
		<date>2024-02-16</date> 
		<day_number>16</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>19</number> 
		<date>2024-02-17</date> 
		<day_number>17</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>20</number> 
		<date>2024-02-18</date> 
		<day_number>18</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>21</number> 
		<date>2024-02-19</date> 
		<day_number>19</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>22</number> 
		<date>2024-02-20</date> 
		<day_number>20</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>23</number> 
		<date>2024-02-21</date> 
		<day_number>21</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>24</number> 
		<date>2024-02-22</date> 
		<day_number>22</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>25</number> 
		<date>2024-02-23</date> 
		<day_number>23</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>26</number> 
		<date>2024-02-24</date> 
		<day_number>24</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>27</number> 
		<date>2024-02-25</date> 
		<day_number>25</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>28</number> 
		<date>2024-02-26</date> 
		<day_number>26</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>29</number> 
		<date>2024-02-27</date> 
		<day_number>27</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>30</number> 
		<date>2024-02-28</date> 
		<day_number>28</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>31</number> 
		<date>2024-02-29</date> 
		<day_number>29</day_number> 
		<in_shown_month> in-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>32</number> 
		<date>2024-03-01</date> 
		<day_number>01</day_number> 
		<in_shown_month> outside-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>33</number> 
		<date>2024-03-02</date> 
		<day_number>02</day_number> 
		<in_shown_month> outside-month</in_shown_month> 
	</day_month> 
	<day_month> 
		<number>34</number> 
		<date>2024-03-03</date> 
		<day_number>03</day_number> 
		<in_shown_month> outside-month</in_shown_month> 
	</day_month> 
</calendar>
