=== TINF23B6/Vereinskalender/xml/events.dtd
<!ELEMENT events (event*)> 

<!ELEMENT event (index, id, event_type, name, date, time_period, type, place, club0?, club1?, points0?, points1?, info_text, notice)> 

<!ELEMENT index (#PCDATA)> 
<!ELEMENT id (#PCDATA)> 
<!ELEMENT event_type (#PCDATA)> 
<!ELEMENT name (#PCDATA)> 
<!ELEMENT date (#PCDATA)> 
<!ELEMENT time_period (#PCDATA)> 
<!ELEMENT type (#PCDATA)> 
<!ELEMENT place (#PCDATA)> 
<!ELEMENT club0 (#PCDATA)> 
<!ELEMENT club1 (#PCDATA)> 
<!ELEMENT points0 (#PCDATA)> 
<!ELEMENT points1 (#PCDATA)> 
<!ELEMENT info_text (#PCDATA)> 
<!ELEMENT notice (#PCDATA)>

=== TINF23B6/Vereinskalender/xml/events.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE events SYSTEM 'events.dtd'> 
<events> 
	<event>
		<index>0</index>
		<id>match_1</id>
		<event_type>match</event_type>
		<name>mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkkkkkkkkkkkkkkkkkkkkkkkk</name>
		<date>2024-11-11</date>
		<time_period>11:11</time_period>
		<type>aüq</type>
		<place>üeä</place>
		<club0>äääe</club0>
		<club1>öüce</club1>
		<points0></points0>
		<points1></points1>
		<info_text>c</info_text>
		<notice></notice>
	</event>
</events>
